[tool.poetry]
name = "gpstools"
version = "0.0.0"
description = "Python routines for working with GPS time series from a variety of processing centers"
authors = ["Scott Henderson <scottyh@uw.edu>"]

[tool.poetry.dependencies]
python = "^3.6"
pandas = "^0.24"
numpy = "^1.18.1"
scipy = "^1.4.1"
matplotlib = "^3.1.2"
geopandas = "^0.6.2"
statsmodels = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8.1"
black = {version = "^19.10b0", allow-prereleases = true}
#dunamai = "^1"


[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
