name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

# Allow one concurrent deployment
concurrency:
  group: 'test'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: gpstools
          cache-environment: true

      - name: Install gpstools
        run: pip install -e ".[dev]"

      - name: Formatting
        continue-on-error: true
        run: black . --check

      - name: PyTest 
        continue-on-error: false
        run: pytest --cov=gpstools